([is_theft_lv1] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_theft_lv1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_theft_lv1)
   (rules [rule22] [rule16] [rule11] [rule7] [rule4] [rule2] [rule1])
   (defeasible-stratum -1))

([is_theft_lv2] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_theft_lv2)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_theft_lv2)
   (rules [rule21] [rule15] [rule10] [rule6] [rule3])
   (defeasible-stratum -1))

([is_theft_lv3] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_theft_lv3)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_theft_lv3)
   (rules [rule20] [rule14] [rule9] [rule5])
   (defeasible-stratum -1))

([is_theft_lv4] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_theft_lv4)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_theft_lv4)
   (rules [rule19] [rule13] [rule8])
   (defeasible-stratum -1))

([is_theft_lv5] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_theft_lv5)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_theft_lv5)
   (rules [rule18] [rule12])
   (defeasible-stratum -1))

([is_theft_lv6] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_theft_lv6)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name is_theft_lv6)
   (rules [rule17])
   (defeasible-stratum 0))

([monetary_penalty] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label monetary_penalty)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name monetary_penalty)
   (rules [pen_lv1_monetary])
   (defeasible-stratum 0))

([min_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name min_imprisonment)
   (rules [pen_lv6_min] [pen_lv5_min] [pen_lv4_min] [pen_lv3_min] [pen_lv2_min] [pen_lv1_min])
   (defeasible-stratum 0))

([max_imprisonment] of defeasible-class
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class rules defeasible-logic-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label max_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [defeasible-class])
   (class-name max_imprisonment)
   (rules [pen_lv5_max] [pen_lv4_max] [pen_lv3_max] [pen_lv2_max] [pen_lv1_max])
   (defeasible-stratum 0))

