([rule1] of defeasible-rule
   (rule-name rule1)
   (original-rule "rule1 ( lc:case ( lc:defendant ?Defendant ) ( lc:is_movable_property \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:is_taken \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:intent_to_appropriate \"true\" ) ) => ( is_theft_lv1 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_theft_lv1)
   (negated no)
   (superior)
   (deductive-rule rule1-deductive)
   (overruled-rule rule1-overruled)
   (system no)
   (support-rule rule1-support)
   (defeasibly-rule rule1-defeasibly)
   (defeated-rule nil))

([rule2] of defeasible-rule
   (rule-name rule2)
   (original-rule "rule2 ( lc:case ( lc:defendant ?Defendant ) ( lc:value_of_stolen_items ?value_of_stolen_items ) ) ( test ( <= ?value_of_stolen_items 150 ) ) => ( not ( is_theft_lv1 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv1)
   (negated yes)
   (superior)
   (deductive-rule rule2-deductive)
   (overruled-rule rule2-overruled)
   (system no)
   (support-rule rule2-support)
   (defeasibly-rule rule2-defeasibly)
   (defeated-rule nil))

([rule3] of defeasible-rule
   (rule-name rule3)
   (original-rule "rule3 ( declare ( superior rule2 rule1 ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:is_movable_property \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:is_taken \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:intent_to_appropriate \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:breaking_and_entering \"true\" ) ) => ( is_theft_lv2 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_theft_lv2)
   (negated no)
   (superior rule2 rule1)
   (deductive-rule rule3-deductive)
   (overruled-rule rule3-overruled)
   (system no)
   (support-rule rule3-support)
   (defeasibly-rule rule3-defeasibly)
   (defeated-rule rule3-defeated))

([rule4] of defeasible-rule
   (rule-name rule4)
   (original-rule "rule4 ( declare ( superior rule1 ) ) ( is_theft_lv2 ( defendant ?Defendant ) ) => ( not ( is_theft_lv1 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv1)
   (negated yes)
   (superior rule1)
   (deductive-rule rule4-deductive)
   (overruled-rule rule4-overruled)
   (system no)
   (support-rule rule4-support)
   (defeasibly-rule rule4-defeasibly)
   (defeated-rule rule4-defeated))

([rule5] of defeasible-rule
   (rule-name rule5)
   (original-rule "rule5 ( lc:case ( lc:defendant ?Defendant ) ( lc:is_movable_property \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:is_taken \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:intent_to_appropriate \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:value_of_stolen_items ?value_of_stolen_items ) ) ( test ( > ?value_of_stolen_items 30000 ) ) => ( is_theft_lv3 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_theft_lv3)
   (negated no)
   (superior)
   (deductive-rule rule5-deductive)
   (overruled-rule rule5-overruled)
   (system no)
   (support-rule rule5-support)
   (defeasibly-rule rule5-defeasibly)
   (defeated-rule nil))

([rule6] of defeasible-rule
   (rule-name rule6)
   (original-rule "rule6 ( declare ( superior rule3 ) ) ( is_theft_lv3 ( defendant ?Defendant ) ) => ( not ( is_theft_lv2 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv2)
   (negated yes)
   (superior rule3)
   (deductive-rule rule6-deductive)
   (overruled-rule rule6-overruled)
   (system no)
   (support-rule rule6-support)
   (defeasibly-rule rule6-defeasibly)
   (defeated-rule rule6-defeated))

([rule7] of defeasible-rule
   (rule-name rule7)
   (original-rule "rule7 ( declare ( superior rule1 ) ) ( is_theft_lv3 ( defendant ?Defendant ) ) => ( not ( is_theft_lv1 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv1)
   (negated yes)
   (superior rule1)
   (deductive-rule rule7-deductive)
   (overruled-rule rule7-overruled)
   (system no)
   (support-rule rule7-support)
   (defeasibly-rule rule7-defeasibly)
   (defeated-rule rule7-defeated))

([rule8] of defeasible-rule
   (rule-name rule8)
   (original-rule "rule8 ( lc:case ( lc:defendant ?Defendant ) ( lc:is_movable_property \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:is_taken \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:intent_to_appropriate \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:caught_in_the_act \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:use_of_force_or_threat \"true\" ) ) => ( is_theft_lv4 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_theft_lv4)
   (negated no)
   (superior)
   (deductive-rule rule8-deductive)
   (overruled-rule rule8-overruled)
   (system no)
   (support-rule rule8-support)
   (defeasibly-rule rule8-defeasibly)
   (defeated-rule nil))

([rule9] of defeasible-rule
   (rule-name rule9)
   (original-rule "rule9 ( declare ( superior rule5 ) ) ( is_theft_lv4 ( defendant ?Defendant ) ) => ( not ( is_theft_lv3 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv3)
   (negated yes)
   (superior rule5)
   (deductive-rule rule9-deductive)
   (overruled-rule rule9-overruled)
   (system no)
   (support-rule rule9-support)
   (defeasibly-rule rule9-defeasibly)
   (defeated-rule rule9-defeated))

([rule10] of defeasible-rule
   (rule-name rule10)
   (original-rule "rule10 ( declare ( superior rule3 ) ) ( is_theft_lv4 ( defendant ?Defendant ) ) => ( not ( is_theft_lv2 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv2)
   (negated yes)
   (superior rule3)
   (deductive-rule rule10-deductive)
   (overruled-rule rule10-overruled)
   (system no)
   (support-rule rule10-support)
   (defeasibly-rule rule10-defeasibly)
   (defeated-rule rule10-defeated))

([rule11] of defeasible-rule
   (rule-name rule11)
   (original-rule "rule11 ( declare ( superior rule1 ) ) ( is_theft_lv4 ( defendant ?Defendant ) ) => ( not ( is_theft_lv1 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv1)
   (negated yes)
   (superior rule1)
   (deductive-rule rule11-deductive)
   (overruled-rule rule11-overruled)
   (system no)
   (support-rule rule11-support)
   (defeasibly-rule rule11-defeasibly)
   (defeated-rule rule11-defeated))

([rule12] of defeasible-rule
   (rule-name rule12)
   (original-rule "rule12 ( lc:case ( lc:defendant ?Defendant ) ( lc:is_movable_property \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:is_taken \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:intent_to_appropriate \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:caught_in_the_act \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:use_of_force_or_threat \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:caused_severe_injury \"true\" ) ) => ( is_theft_lv5 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_theft_lv5)
   (negated no)
   (superior)
   (deductive-rule rule12-deductive)
   (overruled-rule rule12-overruled)
   (system no)
   (support-rule rule12-support)
   (defeasibly-rule rule12-defeasibly)
   (defeated-rule nil))

([rule13] of defeasible-rule
   (rule-name rule13)
   (original-rule "rule13 ( declare ( superior rule8 ) ) ( is_theft_lv5 ( defendant ?Defendant ) ) => ( not ( is_theft_lv4 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv4)
   (negated yes)
   (superior rule8)
   (deductive-rule rule13-deductive)
   (overruled-rule rule13-overruled)
   (system no)
   (support-rule rule13-support)
   (defeasibly-rule rule13-defeasibly)
   (defeated-rule rule13-defeated))

([rule14] of defeasible-rule
   (rule-name rule14)
   (original-rule "rule14 ( declare ( superior rule5 ) ) ( is_theft_lv5 ( defendant ?Defendant ) ) => ( not ( is_theft_lv3 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv3)
   (negated yes)
   (superior rule5)
   (deductive-rule rule14-deductive)
   (overruled-rule rule14-overruled)
   (system no)
   (support-rule rule14-support)
   (defeasibly-rule rule14-defeasibly)
   (defeated-rule rule14-defeated))

([rule15] of defeasible-rule
   (rule-name rule15)
   (original-rule "rule15 ( declare ( superior rule3 ) ) ( is_theft_lv5 ( defendant ?Defendant ) ) => ( not ( is_theft_lv2 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv2)
   (negated yes)
   (superior rule3)
   (deductive-rule rule15-deductive)
   (overruled-rule rule15-overruled)
   (system no)
   (support-rule rule15-support)
   (defeasibly-rule rule15-defeasibly)
   (defeated-rule rule15-defeated))

([rule16] of defeasible-rule
   (rule-name rule16)
   (original-rule "rule16 ( declare ( superior rule1 ) ) ( is_theft_lv5 ( defendant ?Defendant ) ) => ( not ( is_theft_lv1 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv1)
   (negated yes)
   (superior rule1)
   (deductive-rule rule16-deductive)
   (overruled-rule rule16-overruled)
   (system no)
   (support-rule rule16-support)
   (defeasibly-rule rule16-defeasibly)
   (defeated-rule rule16-defeated))

([rule17] of defeasible-rule
   (rule-name rule17)
   (original-rule "rule17 ( lc:case ( lc:defendant ?Defendant ) ( lc:is_movable_property \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:is_taken \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:intent_to_appropriate \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:caught_in_the_act \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:use_of_force_or_threat \"true\" ) ) ( lc:case ( lc:defendant ?Defendant ) ( lc:death_caused \"true\" ) ) => ( is_theft_lv6 ( defendant ?Defendant ) )")
   (condition-classes)
   (conclusion-class is_theft_lv6)
   (negated no)
   (superior)
   (deductive-rule rule17-deductive)
   (overruled-rule rule17-overruled)
   (system no)
   (support-rule rule17-support)
   (defeasibly-rule rule17-defeasibly)
   (defeated-rule nil))

([rule18] of defeasible-rule
   (rule-name rule18)
   (original-rule "rule18 ( declare ( superior rule12 ) ) ( is_theft_lv6 ( defendant ?Defendant ) ) => ( not ( is_theft_lv5 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv5)
   (negated yes)
   (superior rule12)
   (deductive-rule rule18-deductive)
   (overruled-rule rule18-overruled)
   (system no)
   (support-rule rule18-support)
   (defeasibly-rule rule18-defeasibly)
   (defeated-rule rule18-defeated))

([rule19] of defeasible-rule
   (rule-name rule19)
   (original-rule "rule19 ( declare ( superior rule8 ) ) ( is_theft_lv6 ( defendant ?Defendant ) ) => ( not ( is_theft_lv4 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv4)
   (negated yes)
   (superior rule8)
   (deductive-rule rule19-deductive)
   (overruled-rule rule19-overruled)
   (system no)
   (support-rule rule19-support)
   (defeasibly-rule rule19-defeasibly)
   (defeated-rule rule19-defeated))

([rule20] of defeasible-rule
   (rule-name rule20)
   (original-rule "rule20 ( declare ( superior rule5 ) ) ( is_theft_lv6 ( defendant ?Defendant ) ) => ( not ( is_theft_lv3 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv3)
   (negated yes)
   (superior rule5)
   (deductive-rule rule20-deductive)
   (overruled-rule rule20-overruled)
   (system no)
   (support-rule rule20-support)
   (defeasibly-rule rule20-defeasibly)
   (defeated-rule rule20-defeated))

([rule21] of defeasible-rule
   (rule-name rule21)
   (original-rule "rule21 ( declare ( superior rule3 ) ) ( is_theft_lv6 ( defendant ?Defendant ) ) => ( not ( is_theft_lv2 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv2)
   (negated yes)
   (superior rule3)
   (deductive-rule rule21-deductive)
   (overruled-rule rule21-overruled)
   (system no)
   (support-rule rule21-support)
   (defeasibly-rule rule21-defeasibly)
   (defeated-rule rule21-defeated))

([rule22] of defeasible-rule
   (rule-name rule22)
   (original-rule "rule22 ( declare ( superior rule1 ) ) ( is_theft_lv6 ( defendant ?Defendant ) ) => ( not ( is_theft_lv1 ( defendant ?Defendant ) ) )")
   (condition-classes)
   (conclusion-class is_theft_lv1)
   (negated yes)
   (superior rule1)
   (deductive-rule rule22-deductive)
   (overruled-rule rule22-overruled)
   (system no)
   (support-rule rule22-support)
   (defeasibly-rule rule22-defeasibly)
   (defeated-rule rule22-defeated))

([pen_lv1_monetary] of defeasible-rule
   (rule-name pen_lv1_monetary)
   (original-rule "pen_lv1_monetary ( is_theft_lv1 ( defendant ?Defendant ) ) => ( monetary_penalty ( value True ) )")
   (condition-classes)
   (conclusion-class monetary_penalty)
   (negated no)
   (superior)
   (deductive-rule pen_lv1_monetary-deductive)
   (overruled-rule pen_lv1_monetary-overruled)
   (system no)
   (support-rule pen_lv1_monetary-support)
   (defeasibly-rule pen_lv1_monetary-defeasibly)
   (defeated-rule nil))

([pen_lv1_min] of defeasible-rule
   (rule-name pen_lv1_min)
   (original-rule "pen_lv1_min ( is_theft_lv1 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 0 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_lv1_min-deductive)
   (overruled-rule pen_lv1_min-overruled)
   (system no)
   (support-rule pen_lv1_min-support)
   (defeasibly-rule pen_lv1_min-defeasibly)
   (defeated-rule nil))

([pen_lv1_max] of defeasible-rule
   (rule-name pen_lv1_max)
   (original-rule "pen_lv1_max ( is_theft_lv1 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_lv1_max-deductive)
   (overruled-rule pen_lv1_max-overruled)
   (system no)
   (support-rule pen_lv1_max-support)
   (defeasibly-rule pen_lv1_max-defeasibly)
   (defeated-rule nil))

([pen_lv2_min] of defeasible-rule
   (rule-name pen_lv2_min)
   (original-rule "pen_lv2_min ( is_theft_lv2 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_lv2_min-deductive)
   (overruled-rule pen_lv2_min-overruled)
   (system no)
   (support-rule pen_lv2_min-support)
   (defeasibly-rule pen_lv2_min-defeasibly)
   (defeated-rule nil))

([pen_lv2_max] of defeasible-rule
   (rule-name pen_lv2_max)
   (original-rule "pen_lv2_max ( is_theft_lv2 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 8 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_lv2_max-deductive)
   (overruled-rule pen_lv2_max-overruled)
   (system no)
   (support-rule pen_lv2_max-support)
   (defeasibly-rule pen_lv2_max-defeasibly)
   (defeated-rule nil))

([pen_lv3_min] of defeasible-rule
   (rule-name pen_lv3_min)
   (original-rule "pen_lv3_min ( is_theft_lv3 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 2 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_lv3_min-deductive)
   (overruled-rule pen_lv3_min-overruled)
   (system no)
   (support-rule pen_lv3_min-support)
   (defeasibly-rule pen_lv3_min-defeasibly)
   (defeated-rule nil))

([pen_lv3_max] of defeasible-rule
   (rule-name pen_lv3_max)
   (original-rule "pen_lv3_max ( is_theft_lv3 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 10 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_lv3_max-deductive)
   (overruled-rule pen_lv3_max-overruled)
   (system no)
   (support-rule pen_lv3_max-support)
   (defeasibly-rule pen_lv3_max-defeasibly)
   (defeated-rule nil))

([pen_lv4_min] of defeasible-rule
   (rule-name pen_lv4_min)
   (original-rule "pen_lv4_min ( is_theft_lv4 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 1 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_lv4_min-deductive)
   (overruled-rule pen_lv4_min-overruled)
   (system no)
   (support-rule pen_lv4_min-support)
   (defeasibly-rule pen_lv4_min-defeasibly)
   (defeated-rule nil))

([pen_lv4_max] of defeasible-rule
   (rule-name pen_lv4_max)
   (original-rule "pen_lv4_max ( is_theft_lv4 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 8 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_lv4_max-deductive)
   (overruled-rule pen_lv4_max-overruled)
   (system no)
   (support-rule pen_lv4_max-support)
   (defeasibly-rule pen_lv4_max-defeasibly)
   (defeated-rule nil))

([pen_lv5_min] of defeasible-rule
   (rule-name pen_lv5_min)
   (original-rule "pen_lv5_min ( is_theft_lv5 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 3 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_lv5_min-deductive)
   (overruled-rule pen_lv5_min-overruled)
   (system no)
   (support-rule pen_lv5_min-support)
   (defeasibly-rule pen_lv5_min-defeasibly)
   (defeated-rule nil))

([pen_lv5_max] of defeasible-rule
   (rule-name pen_lv5_max)
   (original-rule "pen_lv5_max ( is_theft_lv5 ( defendant ?Defendant ) ) => ( max_imprisonment ( value 15 ) )")
   (condition-classes)
   (conclusion-class max_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_lv5_max-deductive)
   (overruled-rule pen_lv5_max-overruled)
   (system no)
   (support-rule pen_lv5_max-support)
   (defeasibly-rule pen_lv5_max-defeasibly)
   (defeated-rule nil))

([pen_lv6_min] of defeasible-rule
   (rule-name pen_lv6_min)
   (original-rule "pen_lv6_min ( is_theft_lv6 ( defendant ?Defendant ) ) => ( min_imprisonment ( value 10 ) )")
   (condition-classes)
   (conclusion-class min_imprisonment)
   (negated no)
   (superior)
   (deductive-rule pen_lv6_min-deductive)
   (overruled-rule pen_lv6_min-overruled)
   (system no)
   (support-rule pen_lv6_min-support)
   (defeasibly-rule pen_lv6_min-defeasibly)
   (defeated-rule nil))

