([is_theft_lv1-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_theft_lv1)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule22-deductive-gen413] [rule16-deductive-gen407] [rule11-deductive-gen402] [rule7-deductive-gen398] [rule4-deductive-gen395] [rule2-deductive-gen393] [rule1-deductive-gen392]))

([is_theft_lv2-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_theft_lv2)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule21-deductive-gen412] [rule15-deductive-gen406] [rule10-deductive-gen401] [rule6-deductive-gen397] [rule3-deductive-gen394]))

([is_theft_lv3-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_theft_lv3)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule20-deductive-gen411] [rule14-deductive-gen405] [rule9-deductive-gen400] [rule5-deductive-gen396]))

([is_theft_lv4-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_theft_lv4)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule19-deductive-gen410] [rule13-deductive-gen404] [rule8-deductive-gen399]))

([is_theft_lv5-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_theft_lv5)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule18-deductive-gen409] [rule12-deductive-gen403]))

([is_theft_lv6-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label is_theft_lv6)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [rule17-deductive-gen408]))

([monetary_penalty-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label monetary_penalty)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen_lv1_monetary-deductive-gen414]))

([min_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label min_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen_lv6_min-deductive-gen425] [pen_lv5_min-deductive-gen423] [pen_lv4_min-deductive-gen421] [pen_lv3_min-deductive-gen419] [pen_lv2_min-deductive-gen417] [pen_lv1_min-deductive-gen415]))

([max_imprisonment-derived-class] of derived-class-inst
   (class-refs rdfs:isDefinedBy rdfs:Resource rdf:type rdfs:Class rdfs:seeAlso rdfs:Resource rdfs:subClassOf rdfs:Class deductive-rules r-device-rule)
   (aliases rdfs:seeAlso rdfs:isDefinedBy)
   (positive 0)
   (negative 0)
   (positive-derivator)
   (negative-derivator)
   (positive-support)
   (negative-support)
   (positive-overruled)
   (negative-overruled)
   (positive-defeated)
   (negative-defeated)
   (proof nil)
   (uri nil)
   (source rdf)
   (lc:case)
   (lc:defendant)
   (lc:is_movable_property)
   (lc:is_taken)
   (lc:intent_to_appropriate)
   (lc:breaking_and_entering)
   (lc:use_of_force_or_threat)
   (lc:caught_in_the_act)
   (lc:caused_severe_injury)
   (lc:death_caused)
   (lc:value_of_stolen_items)
   (rdfs:isDefinedBy)
   (rdf:type [rdfs:Class])
   (rdf:value)
   (rdfs:comment)
   (rdfs:label max_imprisonment)
   (rdfs:seeAlso)
   (rdfs:subClassOf [derived-class-inst])
   (stratum 0)
   (deductive-rules [pen_lv5_max-deductive-gen424] [pen_lv4_max-deductive-gen422] [pen_lv3_max-deductive-gen420] [pen_lv2_max-deductive-gen418] [pen_lv1_max-deductive-gen416]))

